### ISSUE TITLE
500 when POSTing a tblastx job with default UI params

### ISSUE THREAD

**Issue by jtlong3rd** [VEuPathDB/service-multi-blast#29]
When this is POSTed to `/jobs`...

```
{
  "site": "ToxoDB",
  "config": {
    "softMasking": true,
    "lcaseMasking": false,
    "seg": {
      "locut": 2.2,
      "window": 12,
      "hicut": 2.5
    },
    "maxTargetSeqs": 50,
    "query": "GAATACAGAATACAGAATACA",
    "outFormat": {"format": "single-file-json"},
    "wordSize": 3,
    "matrix": "BLOSUM62",
    "queryGeneticCode": 1,
    "tool": "tblastx",
    "eValue": "10"
  },
  "targets": [{
    "organism": "TgondiiME49",
    "target": "TgondiiME49AnnotatedTranscripts"
  }]
}
```

... this NPE is thrown:

```
Feb 19, 2021 6:04:33 PM org.glassfish.jersey.server.ServerRuntime$Responder mapException
SEVERE: An exception was not mapped due to exception mapper failure. The HTTP 500 response will be returned.
javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
	at org.veupathdb.service.multiblast.service.http.Util.wrapException(Util.java:12)
	at org.veupathdb.service.multiblast.service.http.job.JobCreationService.createJobs(JobCreationService.java:49)
	at org.veupathdb.service.multiblast.service.http.JobService.createJob(JobService.java:270)
	at org.veupathdb.service.multiblast.controller.JobController.postJobs(JobController.java:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:356)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Collection.toArray()" because "c" is null
	at java.base/java.util.ArrayList.<init>(ArrayList.java:181)
	at org.veupathdb.service.multiblast.model.blast.impl.TBlastXConfigImpl.setTaxIDs(TBlastXConfigImpl.java:319)
	at org.veupathdb.service.multiblast.model.blast.impl.TBlastXConfigImpl.setTaxIDs(TBlastXConfigImpl.java:17)
	at org.veupathdb.service.multiblast.service.conv.TBlastxConverter.externalToInternal(TBlastxConverter.java:90)
	at org.veupathdb.service.multiblast.service.conv.TBlastxConverter.toInternal(TBlastxConverter.java:74)
	at org.veupathdb.service.multiblast.service.conv.BlastConverter.externalToInternal(BlastConverter.java:56)
	at org.veupathdb.service.multiblast.service.conv.BlastConverter.toInternal(BlastConverter.java:42)
	at org.veupathdb.service.multiblast.service.conv.JobConverter.externalToInternal(JobConverter.java:104)
	at org.veupathdb.service.multiblast.service.conv.JobConverter.toInternal(JobConverter.java:96)
	at org.veupathdb.service.multiblast.service.http.job.JobCreationService.createJobs(JobCreationService.java:97)
	at org.veupathdb.service.multiblast.service.http.job.JobCreationService.createJobs(JobCreationService.java:47)
	... 28 more
```

**Comment by Foxcapades** [comment]
Fixed on branch [multi-job](https://github.com/VEuPathDB/service-multi-blast/tree/multi-job)

Will close issue when merging into master.
