### ISSUE TITLE
415 when POSTing to /jobs with multipart/form-data

### ISSUE THREAD

**Issue by jtlong3rd** [VEuPathDB/service-multi-blast#30]
This POST to `/jobs` yielded a 415:

```
------WebKitFormBoundaryuNp3fe1B4qBGWY3B
Content-Disposition: form-data; name="properties"

{"site":"PlasmoDB","targets":[{"organism":"Pfalciparum3D7","target":"Pfalciparum3D7AnnotatedTranscripts"}],"config":{"tool":"blastn","task":"blastn","query":"GAATACAGAATACAGAATACA","eValue":"10","maxTargetSeqs":50,"wordSize":11,"softMasking":true,"lcaseMasking":false,"outFormat":{"format":"single-file-json"},"dust":{"enable":true,"level":20,"window":64,"linker":1},"reward":2,"penalty":-3,"gapOpen":5,"gapExtend":2},"description":"My New Job"}
------WebKitFormBoundaryuNp3fe1B4qBGWY3B--
```

Relevant logs:

```
 javax.ws.rs.NotSupportedException: HTTP 415 Unsupported Media Type
	at org.glassfish.jersey.server.spi.internal.ParameterValueHelper.getParameterValues(ParameterValueHelper.java:75) ~[service.jar:1.0.0]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$AbstractMethodParamInvoker.getParamValues(JavaResourceMethodDispatcherProvider.java:109) ~[service.jar:1.0.0]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176) ~[service.jar:1.0.0]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) ~[service.jar:1.0.0]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475) ~[service.jar:1.0.0]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397) ~[service.jar:1.0.0]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) ~[service.jar:1.0.0]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255) [service.jar:1.0.0]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [service.jar:1.0.0]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [service.jar:1.0.0]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) [service.jar:1.0.0]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) [service.jar:1.0.0]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) [service.jar:1.0.0]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) [service.jar:1.0.0]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234) [service.jar:1.0.0]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680) [service.jar:1.0.0]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:356) [service.jar:1.0.0]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200) [service.jar:1.0.0]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569) [service.jar:1.0.0]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549) [service.jar:1.0.0]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: org.glassfish.jersey.message.internal.MessageBodyProviderNotFoundException: MessageBodyReader not found for media type=multipart/form-data;boundary=----WebKitFormBoundaryuNp3fe1B4qBGWY3B, type=interface org.veupathdb.service.multiblast.generated.model.IOMultipartJobRequest, genericType=interface org.veupathdb.service.multiblast.generated.model.IOMultipartJobRequest.
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:208) ~[service.jar:1.0.0]
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:132) ~[service.jar:1.0.0]
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundReadFrom(MappableExceptionWrapperInterceptor.java:49) ~[service.jar:1.0.0]
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:132) ~[service.jar:1.0.0]
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1072) ~[service.jar:1.0.0]
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:885) ~[service.jar:1.0.0]
	at org.glassfish.jersey.server.ContainerRequest.readEntity(ContainerRequest.java:282) ~[service.jar:1.0.0]
	at org.glassfish.jersey.server.internal.inject.EntityParamValueParamProvider$EntityValueSupplier.apply(EntityParamValueParamProvider.java:73) ~[service.jar:1.0.0]
	at org.glassfish.jersey.server.internal.inject.EntityParamValueParamProvider$EntityValueSupplier.apply(EntityParamValueParamProvider.java:56) ~[service.jar:1.0.0]
	at org.glassfish.jersey.server.spi.internal.ParamValueFactoryWithSource.apply(ParamValueFactoryWithSource.java:50) ~[service.jar:1.0.0]
	at org.glassfish.jersey.server.spi.internal.ParameterValueHelper.getParameterValues(ParameterValueHelper.java:68) ~[service.jar:1.0.0]
	... 20 more
```

**Comment by Foxcapades** [comment]
Fixed on branch [multi-job](https://github.com/VEuPathDB/service-multi-blast/tree/multi-job)

Will close issue when merging into master.
