### ISSUE TITLE
Failure when transferring guest jobs to logged in user on dev sites

### ISSUE THREAD

**Issue by ryanrdoherty** [VEuPathDB/service-multi-blast#90]
Got the following error message; may be due to disjoint configs.  If so, improve message, maybe convert to 400 "ID does not exist" or somesuch.
```
[26/Oct/2021|10:42:53] sid:04D48 rid:   62     528ms   173.67.160.39 - ERROR - org.apidb.apicommon.service.services.ApiSessionService:91 - Multi-blast merge jobs request failed
org.gusdb.wdk.model.WdkModelException: Unable to merge multi-blast jobs from guest user 306316720 to registered user 7145453. Service at https://rdoherty.plasmodb.org/multi-blast/link-guest returned 500 with error: {"status":"server-error","message":"HTTP 500 Internal Server Error","requestId":"1EKD4sTdvenTDtPQLXYmuC"}
	at org.apidb.apicommon.service.services.ApiSessionService.transferMultiBlastJobs(ApiSessionService.java:81) [api-common-website-service-1.0.0.jar:?]
	at org.apidb.apicommon.service.services.ApiSessionService.transferOwnership(ApiSessionService.java:36) [api-common-website-service-1.0.0.jar:?]
	at org.gusdb.wdk.service.service.SessionService.processOauthLogin(SessionService.java:123) [wdk-service-1.0.0.jar:?]
```

**Comment by aurreco-uga** [comment]
this seems to work fine but we do get the  wdk logs error

`
[07/Apr/2022|17:20:25] sid:32330 rid: 2376751     409ms    24.181.4.128 - ERROR - org.apidb.apicommon.service.services.ApiSessionService:91 - Multi-blast merge jobs request failed
org.gusdb.wdk.model.WdkModelException: Unable to merge multi-blast jobs from guest user 1024379683 to registered user 376. Service at https://w1.plasmodb.org/multi-blast/link-guest returned 422 with error: {"status":"invalid-input","errors":{"general":["Cannot construct instance of `mb.api.model.IOGuestLink` (although"],"byKey":{}}}
	at org.apidb.apicommon.service.services.ApiSessionService.transferMultiBlastJobs(ApiSessionService.java:81) [api-common-website-service-1.0.0.jar:?]
	at org.apidb.apicommon.service.services.ApiSessionService.transferOwnership(ApiSessionService.java:36) [api-common-website-service-1.0.0.jar:?]
	at org.gusdb.wdk.service.service.SessionService.processOauthLogin(SessionService.java:123) [wdk-service-1.0.0.jar:?]`
